#!/usr/bin/python3
import sys


if __name__ == '__main__':

    if len(sys.argv) != 2:
        print("USAGE: factors file", file=sys.stderr)
        exit(1)
        
    try:
        file1 = open(sys.argv[1], "r")
    except Exception:
        print("Error: Can't open file {}".format(sys.argv[1]), file=sys.stderr)
        exit(1)

    for line in file1:
        try:
            stripped = line.strip()
            if (not len(stripped)):
                continue
            num = int(stripped)
            print('{}=1*{}'.format(num, num))
        except Exception:
            continue
    file1.close()
