#!/usr/bin/python3
import sys


if __name__ == '__main__':
    if len(sys.argv) == 2:
        try:
            file1 = open(sys.argv[1], "r")
        except Exception:
            exit()
        for line in file1:
            splitted = line.split()
            for word in splitted:
                try:
                    num = int(word)
                    print('{}=1*{}'.format(num, num))
                    break
                except Exception:
                    continue
        file1.close()
