#!/usr/bin/python3
''' 
    """actorize as many numbers as possible into a product of two smaller numbers
    """
'''
import sys
from math import isqrt


def fermat_factor2(n):
    if n & 1 == 0:
        return (2, n // 2)

    a = isqrt(n) + 1
    b2 = a**2 - n
    b = isqrt(b2)

    while b**2 != b2:
        a += 1
        b2 = a**2 - n
        b = isqrt(b2)

    return (a + b, a - b)

def main():
    '''
    """Factorize as many numbers as possible into a product of two smaller numbers.

    Returns:
        number: 0  
    """    
    '''

    try:
        with open(sys.argv[1], 'r') as file:
            for line in file:
                try:
                    num = int(line)
                    fact = fermat_factor2(num)
                    print(f"{num}={fact[0]}*{fact[1]}")
                except Exception:
                    pass
    except FileNotFoundError:
        sys.exit(1)
    return 0

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(1)

    main()
